{
	"version": 1573812293,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bgopen-sheet0.png",
		"images/bgload-sheet0.png",
		"images/loadbar.png",
		"images/w-sheet0.png",
		"images/bgquiz-sheet0.png",
		"images/bgscore-sheet0.png",
		"images/home-sheet0.png",
		"images/exit-sheet0.png",
		"images/music-sheet0.png",
		"images/music-sheet1.png",
		"images/sound-sheet0.png",
		"images/sound-sheet1.png",
		"images/into-sheet0.png",
		"images/out-sheet0.png",
		"images/sprite-sheet0.png",
		"media/magic_chime (online-audio-converter (online-audio-converter.com).ogg",
		"media/magic_chime -waw.m4a",
		"media/magic_chime -waw.ogg",
		"media/happy_haunts (online-audio-converter.com).ogg",
		"media/happy_haunts -waw.m4a",
		"media/happy_haunts -waw.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}